# TravisCI configuration for arnaud-lb/php-memory-profiler

if: "branch = v2"

language: "php"
os:
    - "linux"
dist: "bionic"

addons:
    apt:
        packages:
            - "libjudy-dev"
            - "libonig-dev"
            - "libzip-dev"

php:
    - "8.0"
    - "7.4"
    - "7.3"
    - "7.2
    - "7.1"

jobs:
    fast_finish: true

before_install:
    - "phpenv config-rm xdebug.ini"

install:
    - "phpize"
    - "CFLAGS='-Wall -Werror' ./configure"
    - "make"

script:
    - "php --ri memprof"
    - "REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=\"$(realpath \"$(which php)\")\" php run-tests.php -s -q --show-diff"
