# TravisCI configuration for arnaud-lb/php-memory-profiler

if: "branch = v2"

language: "php"
os:
    - "linux"
dist: "bionic"

addons:
    apt:
        packages:
            - "libjudy-dev"
            - "libonig-dev"
            - "libzip-dev"

php:
    - "8.0"
    - "7.4"
    - "7.3"
    - "7.2"
    - "7.1"

jobs:
    fast_finish: true

cache:
    directories:
        - "${HOME}/.phpenv/"

before_install:
    - |
        # Using PHP non-ZTS
        PHP_VERSION="$(php -r 'echo PHP_VERSION;')"
        if ! [ -f "${HOME}/.phpenv/php-non-zts-built" ]; then
            echo "Building PHP ZTS ${PHP_VERSION} ..."
            git clone git://github.com/php-build/php-build.git "${HOME}/.phpenv/plugins/php-build"
            phpenv install --verbose --force "${PHP_VERSION}"
            rm -rf "${HOME}/.phpenv/plugins/php-build"
            touch "${HOME}/.phpenv/php-non-zts-built"
        fi
        phpenv rehash
        phpenv global "${PHP_VERSION}"
        phpenv config-rm xdebug.ini
        php -v

install:
    - "phpize"
    - "CFLAGS=\"-Wall -Werror\" ./configure"
    - "make"
    - "echo \"extension = $(realpath modules/memprof.so)\" >modules/memprof.ini"
    - "phpenv config-add modules/memprof.ini"

script:
    - "php --ri memprof"
    - "REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=\"$(realpath \"$(which php)\")\" php run-tests.php -s -q --show-diff"
