name: Feature request
description: Create a feature request
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please describe the requested feature and why it should be included in php-memprof."
    validations:
      required: true
