name: 'Package'

on:
    pull_request:

jobs:
    package:
        name: 'Package'
        runs-on: 'ubuntu-20.04'
        steps:
            - name: 'Check out repository'
              uses: 'actions/checkout@v2'
              with:
                  path: 'ext'

            - name: 'Install dependencies'
              run: 'sudo apt-get -y install php7.4-dev libjudy-dev'

            - name: 'Package and verify package'
              run: './ext/.github/workflows/package/package.sh'

            - name: 'Archive package'
              uses: 'actions/upload-artifact@v2'
              with:
                  path: 'ext/memprof.tgz'
